# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2d709790d2338b13eaf458ae40f3ba2b7f0ab2ebbdbe29cd87e28c61b582c1762cb5110e37694b5d32c2ac93805977e14d65acc23f3dc029804bd387d39f3f1b

test:
  secret_key_base: 08b35c27c3705f10622568558214bee2c936d847d40b65c95bf0bf818312eef1a695679053fdb9e6c71da544d6abbb16fa5efcccc6375d665251b932147a5317

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
